### ISSUE TITLE
无法正常运行   

### ISSUE THREAD

**Issue by supermebing** [jpush/janalytics-flutter-plugin#2]
unning pod install...                                              8.5s
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Fetching external sources
    -> Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
    -> Fetching podspec for `janalytics` from `.symlinks/plugins/janalytics/ios`
    -> Fetching podspec for `package_info` from `.symlinks/plugins/package_info/ios`

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only
      perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_e_2_9.txt exists! Returning local because checking
      is only perfomed in repo update
      CDN: trunk Relative path: Specs/e/2/9/JAnalytics/2.1.2/JAnalytics.podspec.json exists! Returning
      local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/e/2/9/JAnalytics/2.1.2/JAnalytics.podspec.json exists! Returning
      local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/e/2/9/JAnalytics/2.1.0/JAnalytics.podspec.json exists! Returning
      local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/e/2/9/JAnalytics/2.0.0/JAnalytics.podspec.json exists! Returning
      local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/e/2/9/JAnalytics/1.2.1/JAnalytics.podspec.json exists! Returning
      local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/e/2/9/JAnalytics/1.2.0/JAnalytics.podspec.json exists! Returning
      local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/e/2/9/JAnalytics/1.1.3/JAnalytics.podspec.json exists! Returning
      local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/e/2/9/JAnalytics/1.1.2/JAnalytics.podspec.json exists! Returning
      local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_9_2_f.txt exists! Returning local because checking
      is only perfomed in repo update
      CDN: trunk Relative path: Specs/9/2/f/JCore/2.1.4/JCore.podspec.json exists! Returning local
      because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/9/2/f/JCore/2.1.4/JCore.podspec.json exists! Returning local
      because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/9/2/f/JCore/2.1.4-noidfa/JCore.podspec.json exists! Returning
      local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/9/2/f/JCore/2.1.2/JCore.podspec.json exists! Returning local
      because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/9/2/f/JCore/2.1.1/JCore.podspec.json exists! Returning local
      because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/9/2/f/JCore/2.1.0/JCore.podspec.json exists! Returning local
      because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/9/2/f/JCore/2.0.2/JCore.podspec.json exists! Returning local
      because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/9/2/f/JCore/2.0.1/JCore.podspec.json exists! Returning local
      because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/9/2/f/JCore/2.0.0/JCore.podspec.json exists! Returning local
      because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/9/2/f/JCore/1.2.6/JCore.podspec.json exists! Returning local
      because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/9/2/f/JCore/1.2.5/JCore.podspec.json exists! Returning local
      because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/9/2/f/JCore/1.2.2/JCore.podspec.json exists! Returning local
      because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/9/2/f/JCore/1.2.1/JCore.podspec.json exists! Returning local
      because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/9/2/f/JCore/1.2.0/JCore.podspec.json exists! Returning local
      because checking is only perfomed in repo update

    Comparing resolved specification to the sandbox manifest
      A Flutter
      A JAnalytics
      A JCore
      A janalytics
      A package_info

    Downloading dependencies

    -> Installing Flutter (1.0.0)

    -> Installing JAnalytics (2.1.2)
      > Copying JAnalytics from
      `/Users/bing/Library/Caches/CocoaPods/Pods/Release/JAnalytics/2.1.2-46c69` to `Pods/JAnalytics`

    -> Installing JCore (2.1.4)
      > Copying JCore from `/Users/bing/Library/Caches/CocoaPods/Pods/Release/JCore/2.1.4-d345c` to
      `Pods/JCore`

    -> Installing janalytics (0.0.1)

    -> Installing package_info (0.0.1)
      - Running pre install hooks

    Generating Pods project
      - Creating Pods project
      - Installing files into Pods project
        - Adding source files
        - Adding frameworks
        - Adding libraries
        - Adding resources
        - Adding development pod helper files
        - Linking headers
      - Installing Pod Targets
        - Installing target `Flutter` iOS 8.0
        - Installing target `JAnalytics` iOS 7.0
        - Installing target `JCore` iOS 7.0
        - Installing target `janalytics` iOS 8.0
          - Generating dummy source at `Pods/Target Support Files/janalytics/janalytics-dummy.m`
        - Installing target `package_info` iOS 8.0
          - Generating module map file at `Pods/Target Support
          Files/package_info/package_info.modulemap`
          - Generating umbrella header at `Pods/Target Support
          Files/package_info/package_info-umbrella.h`
          - Generating dummy source at `Pods/Target Support Files/package_info/package_info-dummy.m`
      - Installing Aggregate Targets
        - Installing target `Pods-Runner` iOS 8.0
          - Generating dummy source at `Pods/Target Support Files/Pods-Runner/Pods-Runner-dummy.m`
      - Generating deterministic UUIDs
      - Stabilizing target UUIDs
      - Running post install hooks
        - Podfile
      - Writing Xcode project file to `Pods/Pods.xcodeproj`
      Cleaning up sandbox directory
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only
      perfomed in repo update

    ――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

    ### Command

    ```
    /usr/local/bin/pod install --verbose
    ```

    ### Report

    * What did you do?

    * What did you expect to happen?

    * What happened instead?

    ### Stack

    ```
       CocoaPods : 1.8.4
            Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
        RubyGems : 2.5.2.3
            Host : Mac OS X 10.14.6 (18G87)
           Xcode : 11.2.1 (11B500)
             Git : git version 2.23.0
    Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
    Repositories : trunk - CDN - https://cdn.cocoapods.org/
    ```

    ### Plugins

    ```
    cocoapods-deintegrate : 1.0.4
    cocoapods-plugins     : 1.0.0
    cocoapods-search      : 1.0.0
    cocoapods-stats       : 1.1.0
    cocoapods-trunk       : 1.4.1
    cocoapods-try         : 1.1.0
    ```

    ### Podfile

    ```ruby
    # Using a CDN with CocoaPods 1.7.2 or later can save a lot of time on pod installation, but it's
    experimental rather than the default.
    # source 'https://cdn.cocoapods.org/'

    # Uncomment this line to define a global platform for your project
    # platform :ios, '9.0'
    platform :ios, '8.0'
    # CocoaPods analytics sends network stats synchronously affecting flutter build latency.
    ENV['COCOAPODS_DISABLE_STATS'] = 'true'

    project 'Runner', {
      'Debug' => :debug,
      'Profile' => :release,
      'Release' => :release,
    }

    def parse_KV_file(file, separator='=')
      file_abs_path = File.expand_path(file)
      if !File.exists? file_abs_path
        return [];
      end
      pods_ary = []
      skip_line_start_symbols = ["#", "/"]
      File.foreach(file_abs_path) { |line|
          next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
          plugin = line.split(pattern=separator)
          if plugin.length == 2
            podname = plugin[0].strip()
            path = plugin[1].strip()
            podpath = File.expand_path("#{path}", file_abs_path)
            pods_ary.push({:name => podname, :path => podpath});
          else
            puts "Invalid plugin specification: #{line}"
          end
      }
      return pods_ary
    end

    target 'Runner' do
      #use_frameworks!

      # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
      # referring to absolute paths on developers' machines.
      system('rm -rf .symlinks')
      system('mkdir -p .symlinks/plugins')

      # Flutter Pods
      generated_xcode_build_settings = parse_KV_file('./Flutter/Generated.xcconfig')
      if generated_xcode_build_settings.empty?
        puts "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter
        pub get is executed first."
      end
      generated_xcode_build_settings.map { |p|
        if p[:name] == 'FLUTTER_FRAMEWORK_DIR'
          symlink = File.join('.symlinks', 'flutter')
          File.symlink(File.dirname(p[:path]), symlink)
          pod 'Flutter', :path => File.join(symlink, File.basename(p[:path]))
        end
      }

      # Plugin Pods
      plugin_pods = parse_KV_file('../.flutter-plugins')
      plugin_pods.map { |p|
        symlink = File.join('.symlinks', 'plugins', p[:name])
        File.symlink(p[:path], symlink)
        pod p[:name], :path => File.join(symlink, 'ios')
      }
    end

    # Prevent Cocoapods from embedding a second Flutter framework and causing an error with the new
    Xcode build system.
    install! 'cocoapods', :disable_input_output_paths => true

    post_install do |installer|
      installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
      end
    end
    ```

    ### Error

    ```
    Errno::ENOENT - No such file or directory @ rb_sysopen -
    /Users/bing/Desktop/example/ios/Pods/Local Podspecs/janalytics.podspec.json
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/specification.rb:646:in
    `read'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/specification.rb:646:in
    `checksum'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/lockfile.rb:533:in `block in
    generate_checksums'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/lockfile.rb:532:in `each'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/lockfile.rb:532:in
    `generate_checksums'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/lockfile.rb:428:in
    `generate'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:744:in
    `generate_lockfile'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:752:in `write_lockfiles'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:299:in
    `generate_pods_project'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:173:in `integrate'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:162:in `install!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.3.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:22:in `load'
    /usr/local/bin/pod:22:in `<main>'
    ```

    ――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

    [!] Oh no, an error occurred.

    Search for existing GitHub issues similar to yours:
    https://github.com/CocoaPods/CocoaPods/search?q=No+such+file+or+directory+%40+rb_sysopen+-+%2FUser
    s%2Fbing%2FDesktop%2Fexample%2Fios%2FPods%2FLocal+Podspecs%2Fjanalytics.podspec.json&type=Issues

    If none exists, create a ticket, with the template displayed above, on:
    https://github.com/CocoaPods/CocoaPods/issues/new

    Be sure to first read the contributing guide for details on how to properly submit a ticket:
    https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

    Don't forget to anonymize any private data!

    Looking for related issues on cocoapods/cocoapods...
    Found no similar issues. To create a new issue, please visit:
    https://github.com/cocoapods/cocoapods/issues/new

Error running pod install
Error launching application on iPhone 11 Pro.

**Comment by zhangruiyu** [comment]
同样问题 关键还不维护

**Comment by 651619114** [comment]
这个问题你们解决了么

**Comment by Linspirit98** [comment]
/Users/bing/Desktop/example/ios/Pods/Local Podspecs/janalytics.podspec.json

你需要手动拖动janalytics.podspec.json这个文件到上面的地址。
在这里：https://github.com/jpush/janalytics-flutter-plugin/blob/c55669f94a155b344e09c7da8b7fcac551fbed64/ios/janalytics.podspec

我工程pod里面的这些文件（包括podspec）都是自动生成的，每次update或者install我不知道是不是每次都要手动拖这个文件进来。希望这个问题官方以后能解决一下？或者更新更新版本？谢谢。

**Comment by yukirin000** [comment]
demo能运行 不用pub集成下载到本地集成就行了

**Comment by RA1NO3O** [comment]
#12

**Comment by RA1NO3O** [comment]
> 这个问题你们解决了么

#12 可以看下这个issue。
