### ISSUE TITLE
Errno::ENOENT - No such file or directory @ rb_sysopen - ios/Pods/Local Podspecs/janalytics.podspec.json

### ISSUE THREAD

**Issue by kris1919** [jpush/janalytics-flutter-plugin#7]
### Stack

```
   CocoaPods : 1.9.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.4 (19E287)
       Xcode : 11.4.1 (11E503a)
         Git : git version 2.24.2 (Apple Git-127)
```

### Error

```
Errno::ENOENT - No such file or directory @ rb_sysopen - ios/Pods/Local Podspecs/janalytics.podspec.json
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/specification.rb:673:in `read'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/specification.rb:673:in `checksum'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/lockfile.rb:533:in `block in generate_checksums'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/lockfile.rb:532:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/lockfile.rb:532:in `generate_checksums'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/lockfile.rb:428:in `generate'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:744:in `generate_lockfile'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:752:in `write_lockfiles'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:164:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

### flutter doctor
```
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.4 19E287, locale zh-Hans-CN)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[!] Android Studio (version 3.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.46.1)
[✓] Connected device (2 available)
```

**Comment by TerryAsh** [comment]
先在 yaml中去除，然后pub get；再添加依赖，最后pub get

**Comment by zingwin** [comment]
> 先在 yaml中去除，然后pub get；再添加依赖，最后pub get

不管用哟

**Comment by zingwin** [comment]
什么时候改正啊。。。。。

**Comment by zingwin** [comment]
加入janalytics: ^2.0.1   iOS就编译失败

**Comment by vecharm** [comment]
我也出现了这个问题，很奇怪，jpush不会，我试了很多方法都不行

**Comment by vecharm** [comment]
我解决了，我fork了项目，然后改了podspec的名字

**Comment by lh9403** [comment]
> 我解决了，我fork了项目，然后改了podspec的名字

我直接把项目下下来，然后删了example，改了yaml路径，还是不行啊

**Comment by lh9403** [comment]
@vecharm

**Comment by vecharm** [comment]
> > 我解决了，我fork了项目，然后改了podspec的名字
> 
> 我直接把项目下下来，然后删了example，改了yaml路径，还是不行啊

不是yaml的路径问题，是ios的local podspec 它不会生成，应该是和现有的冲突了，你改个不一样的名字就好了

**Comment by lh9403** [comment]
> > > 我解决了，我fork了项目，然后改了podspec的名字
> > 
> > 
> > 我直接把项目下下来，然后删了example，改了yaml路径，还是不行啊
> 
> 不是yaml的路径问题，是ios的local podspec 它不会生成，应该是和现有的冲突了，你改个不一样的名字就好了

现在又开始换了个问题报错，No podspec .... JCore.podspec.json，问下你同时用了推送么？

**Comment by WALL-E-WEB** [comment]
> > > > 我解决了，我fork了项目，然后改了podspec的名字
> > > 
> > > 
> > > 我直接把项目下下来，然后删除了例子，改了yaml路径，还是不行啊
> > 
> > 
> > 不是yaml的路径问题，是ios的本地podspec它不会生成，应该是和现有的冲突了，你改个不一样的名字就好了
> 
> 现在又开始换了个问题报错，没有podspec .... JCore.podspec.json，问下你同时用了推动么？

我也遇到这个了,不知道怎么解决

**Comment by vecharm** [comment]
> > > > 我解决了，我fork了项目，然后改了podspec的名字
> > > 
> > > 
> > > 我直接把项目下下来，然后删了example，改了yaml路径，还是不行啊
> > 
> > 
> > 不是yaml的路径问题，是ios的local podspec 它不会生成，应该是和现有的冲突了，你改个不一样的名字就好了
> 
> 现在又开始换了个问题报错，No podspec .... JCore.podspec.json，问下你同时用了推送么？

是的，也接了推送，你的问题可能是你改错导致的e

**Comment by huangsongyao** [comment]
试试先把.yaml文件的这个janalytics相关的插件先注解了，然后pod install一下把除了janalytics这个插件外的其他插件download到iOS的主体工厂，跟着再把janalytics这个插件的注解打开，在.yaml文件中重新引用，最后再执行一次pod install来单独下载janalytics这个插件到iOS的主体工程里。

**Comment by hezhuowei** [comment]
> 试试先把.yaml文件的这个janalytics相关的插件先注解了，然后pod install一下把除了janalytics这个插件外的其他插件download到iOS的主体工厂，跟着再把janalytics这个插件的注解打开，在.yaml文件中重新引用，最后再执行一次pod install来单独下载janalytics这个插件到iOS的主体工程里。

亲测有效
